fine/__init__.py
from .fine import Fine

fine/blueprints.py
import os
from .parser import Presentation
from flask import (Blueprint, current_app, render_template,
                   send_from_directory, url_for)


blueprint = Blueprint('fine', __name__)


@blueprint.route('/')
def index():
    meta = current_app.config.get('META')
    source_path = os.path.join(
        current_app.root_path,
        current_app.config['SOURCE_DIR']
    )

    contents = []
    for each in os.listdir(source_path):
        if each.endswith('.md'):
            path = os.path.join(source_path, each)
            with open(path, 'r') as f:
                pre = Presentation(f.read())

            configs = pre.meta
            configs['file'] = each[:-3]
            contents.append(configs)

    return render_template('index.html', contents=contents, meta=meta)


@blueprint.route('/media/<filename>')
def get_img(filename):
    media = os.path.join(current_app.root_path,
                         current_app.config.get('MEDIA_DIR'))
    return send_from_directory(media, filename)

@blueprint.route('/revealjs/<path:filename>')
def revealjs(filename):
    static_path = os.path.join(os.path.dirname(__file__), 'static/revealjs')
    return send_from_directory(static_path, filename)

@blueprint.route('/<name>/')
def presentation(name):
    defaults = current_app.config['REVEAL']
    md_extensions = current_app.config['MARKDOWN']
    configs = defaults['config']
    theme = defaults['theme']

    name, _ = os.path.splitext(name)
    filepath = os.path.join(
        current_app.root_path,
        current_app.config['SOURCE_DIR'],
        name + '.md'
    )

    with open(filepath, 'r') as f:
        pre = Presentation(**md_extensions)
        pre.parse(f.read())

    if 'reveal' in pre.meta:
        if 'config' in pre.meta['reveal']:
            configs.update(pre.meta['reveal']['config'])
        if 'theme' in pre.meta['reveal']:
            theme = pre.meta['reveal']['theme']

    theme = (url_for('fine.revealjs', filename='css/theme/') +
             theme + '.css')

    context = {
        'meta': pre.meta,
        'frames': pre.frames,
        'config': configs,
        'theme': theme,
    }
    return render_template('presentation.html', **context)

fine/parser/__init__.py
from .presentation import Presentation
from .frame import Frame

fine/templates/index.html
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <title>{{ meta.title }}</title>

    <meta name="description" content="{{ meta.description }}">
    <meta name="author" content="{{ meta.author }}">

    <meta name="apple-mobile-web-app-capable" content="yes" />
    <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent" />

    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, minimal-ui">

    <!-- Bootstrap -->

    <link rel="stylesheet" href="https://cdn.bootcss.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u"
        crossorigin="anonymous">

    <script src="https://cdn.bootcss.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa"
        crossorigin="anonymous"></script>

    <style type="text/css">
        body {
            color: white;
            background-color: rgb(37, 37, 37);
            font-size: 30px;
            line-height: 1.5em;
            margin: 1% 20% 1%;
        }

        .description,
        .intro {
            font-size: 25px;
            line-height: 1.2em;
        }

        .footer {
            font-size: 20px;
            line-height: 1em;
        }
    </style>
</head>

<body>
    <div class="page-header">
        <h1>Roger's Slides</h1>
    </div>
    <div class="list-group">
        <p class="intro">
            The following are my slides, they are generated from
            <a href="https://en.wikipedia.org/wiki/Markdown">Markdown</a>. This generator is called fine, it is written based on
            <a href="https://github.com/humrochagf/flask-reveal">flask-reveal</a> with some modifications.
        </p>

        {% for slide in contents %}
        <a href="{{ url_for('fine.presentation', name=slide['file']) }}" class="list-group-item" target="view_window">
            <h3 class="list-group-item-heading">
                <strong>{{ slide['title']|safe }}</strong>
                {% if 'new' in slide and slide['new']%}
                <span class="label label-default pull-right">New</span>
                {% endif %}
            </h3>
            <i style="color: #6fa8dc; font-size: 22px">{{ slide['subtitle']|safe }}</i>
            <p class="list-group-item-text description">{{ slide['description']|safe }}</p>
        </a>
        {% endfor %}

        <div class="row">
            <hr>
            <div class="col-lg-12 footer">
                <p class="muted">
                    © 2017 All rights reserved. Made with
                    <a href="http://flask.pocoo.org/">flask</a> and
                    <a href="https://revealjs.com/">reveal.js</a>
                </p>
            </div>
        </div>
    </div>

</body>

</html>

fine/templates/presentation.html
<!doctype html>
<html lang="en">

  <head>
    <!-- Metadata about the presentation -->
    <meta charset="utf-8">

    <title>{{ meta.title }}</title>

    <meta name="description" content="{{ meta.description }}">
    <meta name="author" content="{{ meta.author }}">

    <meta name="apple-mobile-web-app-capable" content="yes" />
    <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent" />

    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, minimal-ui">

    <!-- Presentation Styles -->
    <link rel="stylesheet" href="{{ url_for('fine.revealjs', filename='css/reveal.css') }}">
    <link rel="stylesheet" href="{{ theme }}" id="theme">

    <!-- For syntax highlighting -->
    <link rel="stylesheet" href="{{ url_for('fine.revealjs', filename='lib/css/zenburn.css') }}">

    <!-- Printing and PDF exports -->
    <script>
      var link = document.createElement( 'link' );
      link.rel = 'stylesheet';
      link.type = 'text/css';
      link.href = window.location.search.match( /print-pdf/gi ) ? "{{ url_for('fine.revealjs', filename='css/print/pdf.css') }}" : "{{ url_for('fine.revealjs', filename='css/print/paper.css') }}";
      document.getElementsByTagName( 'head' )[0].appendChild( link );
    </script>

    <!--[if lt IE 9]>
    <script src="{{ url_for('fine.revealjs', filename='lib/js/html5shiv.js') }}"></script>
    <![endif]-->

  </head>

  <body>
    <!-- Presentation body -->
    <div class="reveal">
      <!-- Any section element inside of this container is displayed as a slide -->
      <div class="slides">
        {% for frame in frames %}
          <section {{ frame.attrs|safe }}>
              {{ frame.html|safe }}

              <aside class="notes">
                {{ frame.note|safe }}
              </aside>
          </section>
        {% endfor %}
      </div>

    </div>

    <!-- Scripts loaded after the content -->
    <script src="{{ url_for('fine.revealjs', filename='lib/js/head.min.js') }}"></script>
    <script src="{{ url_for('fine.revealjs', filename='js/reveal.js') }}"></script>

    <script>
      // Full list of configuration options available here:
      // https://github.com/hakimel/reveal.js#configuration
      Reveal.initialize({
        {% for config_name, value in config.items() %}
          {% if value == true %}
            {{ config_name }}: true,
          {% elif value == false %}
            {{ config_name }}: false,
          {% elif value is number %}
            {{ config_name }}: {{ value }},
          {% else %}
            {{ config_name }}: '{{ value }}',
          {% endif %}
        {% endfor %}

        math: {
          mathjax: 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js',
          config: 'TeX-AMS_HTML-full'  // See http://docs.mathjax.org/en/latest/config-files.html
        },

        // Optional libraries used to extend on reveal.js
        dependencies: [
          { src: '{{ url_for("fine.revealjs", filename="lib/js/classList.js") }}', condition: function() { return !document.body.classList; } },
          { src: '{{ url_for("fine.revealjs", filename="plugin/markdown/marked.js") }}', condition: function() { return !!document.querySelector( '[data-markdown]' ); } },
          { src: '{{ url_for("fine.revealjs", filename="plugin/markdown/markdown.js") }}', condition: function() { return !!document.querySelector( '[data-markdown]' ); } },
          { src: '{{ url_for("fine.revealjs", filename="plugin/highlight/highlight.js") }}', async: true, callback: function() { hljs.initHighlightingOnLoad(); } },
          { src: '{{ url_for("fine.revealjs", filename="plugin/zoom-js/zoom.js") }}', async: true },
          { src: '{{ url_for("fine.revealjs", filename="plugin/notes/notes.js") }}', async: true },
          { src: '{{ url_for("fine.revealjs", filename="plugin/math/math.js") }}', async: true }
        ]
      });
    </script>

  </body>
</html>